---
title: "spray-shiny"
output: html_document
date: '2022-07-22'
---

```{r data}
library(baseballr)
library(tidyverse)
library(ggplot2)
library(reshape2)
library(shiny)
start <- "2022-04-07"
current <- Sys.Date()
br_data <- daily_batter_bref(start, current)

#league average data table
league_ave <- br_data %>%
  filter(!is.na(BA)) %>% 
  summarise(Age = round(mean(Age), 1), G = round(mean(G), 1), PA = round(mean(PA), 1), AB = round(mean(AB), 1),
            R = round(mean(R), 1), H = round(mean(H), 1), Singles = round(mean(X1B), 1), Doubles = round(mean(X2B), 1), 
            Triples = round(mean(X3B), 1), HR = round(mean(HR), 1), RBI = round(mean(RBI), 1), BB = round(mean(BB), 1), 
            SO = round(mean(SO), 1), SB = round(mean(SB), 1), BA = round(sum(br_data$H)/sum(br_data$AB), 3), 
            OBP = round((sum(br_data$H)+sum(br_data$BB)+sum(br_data$HBP))/(sum(br_data$AB)+sum(br_data$BB)+sum(br_data$HBP)+sum(SF)), 3), 
            SLG = round((sum(X1B)+2*sum(X2B)+3*sum(X3B)+4*sum(br_data$HR))/sum(br_data$AB), 3),
            OPS = round(OBP+SLG, 3))

#get qualifying list of players
qualifiers <- br_data %>%
  mutate(ABPG = AB/G) %>% #should be 3.1AB/Team game played, but not sure how to get that
  filter(ABPG >= 3.1)

willy <- scrape_statcast_savant(start, current, playerid = playerid_lookup(last_name = "Contreras", first_name = "Willson")$mlbam_id)
willy_br <- br_data %>% filter(Name == "Willson Contreras")
cs <- scrape_statcast_savant(start, current, playerid = playerid_lookup(last_name = "Seager", first_name = "Corey")$mlbam_id) %>% 
            mutate(result = case_when(grepl("out", des) | grepl("error", des) | grepl("fielder's choice", des) ~ "Out",
                                      grepl("single", des) ~"Single",
                                      grepl("double", des) ~"Double",
                                      grepl("triple", des) ~ "Triple",
                                      grepl("homer", des) | grepl("grand slam", des)~ "Homerun"))
cs_br <- br_data %>% 
  filter(Name == "Corey Seager")
```

```{r functions}
#graphing slashline bargraph
graph_slashline2 = function(pt){
  nt <- data.frame(type=c("AVG", "AVG", "OBP", "OBP", "SLG", "SLG", "OPS", "OPS"),
                   temp =c(pt$Name, "LgAvg", pt$Name, "LgAvg", pt$Name, "LgAvg", pt$Name, "LgAvg"),
                   data = c(pt$BA, league_ave$BA, pt$OBP, league_ave$OBP, pt$SLG, league_ave$SLG, pt$OPS, league_ave$OPS))
  ggplot(nt, aes(x=factor(type, level=c("AVG", "OBP", "SLG", "OPS")), y=data, fill=temp))+
    geom_col(position = position_dodge())+
    scale_fill_manual(values= c("#3db5ff", "#0099f9"), name ="")+
    geom_text(aes(label=data), position = position_dodge(0.9), vjust=-.5, size = 4)+
    labs(x="", y="", title = paste0("Slash Line of ", pt$Name, " Against League Average"))
}

#Gets stat rankings
calc_rank = function(pt, stat){
  if(stat %in% c("BA", "OBP", "SLG", "OPS")){
    temp=qualifiers[order(desc(qualifiers[,stat])),]
    ret = list(which(temp$Name == pt$Name), round(which(temp$Name == pt$Name)*100/nrow(temp), 2))
  }
  else{
    temp=br_data[order(desc(br_data[,stat])),]
    ret =  which(temp$Name == pt$Name)
  }
  return(ret)
}

#Get spray chart
spraychart <- function(pt)
  ggspraychart(
    pt,
    x_value = "hc_x",
    y_value = "-hc_y",
    fill_value = "result",
    point_size = 2.5
  ) +
  scale_fill_manual(breaks = c("Out", "Single", "Double", "Triple", "Homerun"), 
                    values= c("#c62828", "#fdd835", "#1976d2", "#388e3c", "#ffa726"), 
                    name="")

#get shift percentage
shift_perc = function(pt, pt2){
  shift <- pt %>% 
    filter(if_fielding_alignment == "Infield shift") %>% 
    count()
  
  pa_shift <- pt %>% 
    filter(if_fielding_alignment == "Infield shift",
           events != "",
           events != "caught_stealing_2b",
           events != "caught_stealing_3b") %>% 
    count()
  
  strat_shift <- pt %>% 
    filter(if_fielding_alignment == "Strategic") %>% 
    count()
  
  pa_strat_shift <- pt %>% 
    filter(if_fielding_alignment == "Strategic",
           events != "",
           events != "caught_stealing_2b",
           events != "caught_stealing_3b") %>% 
    count()
  
  pa_no_shift <- pt %>% 
    filter(if_fielding_alignment != "Infield shift",
           events != "",
           events != "caught_stealing_2b",
           events != "caught_stealing_3b") %>% 
    count()
  
  pa_shift = pa_shift$n
  pa_no_shift = pa_no_shift$n
  
  perc_byplay = round(shift$n*100/nrow(pt), 2)
  perc_bypa = round((pa_shift*100)/(pa_shift+pa_no_shift), 2)
  perc_strategic_byplay = round((strat_shift$n*100)/nrow(pt), 2)
  perc_strategic_bypa = round((pa_strat_shift$n*100)/(pa_no_shift+pa_shift), 2)
  

  
  ret = data.frame(pa_shift, pa_no_shift, perc_byplay, perc_bypa, perc_strategic_byplay, perc_strategic_bypa)
  return(ret)
}

get_shift_stats = function(pt){
  temp <- pt %>% 
    filter(events != "",
           events != "caught_stealing_2b",
           events != "caught_stealing_3b",
           if_fielding_alignment != "Standard") %>% 
    mutate(hit = case_when(events == "single" | events == "double" | events == "triple" | events == "home_run" ~ "Y",
                           TRUE ~ "N"))
  ab_ws = (nrow(temp)-sum(temp$events=="hit_by_pitch")-sum(temp$events == "sac_fly")-sum(temp$events == "walk"))
  ba_ws = round(sum(temp$hit == "Y")/ab_ws, 3)
  obp_ws = round((sum(temp$hit == "Y")+sum(temp$events == "walk")+sum(temp$events == "hit_by_pitch")) /nrow(temp), 3)
  slg_ws = round((sum(temp$events == "single")+2*sum(temp$events == "double")+3*sum(temp$events == "triple")+4*sum(temp$events == "home_run"))/ab_ws, 3)
  ops_ws = round(obp_ws+slg_ws, 3)
  
  temp2 <- pt %>% 
    filter(events != "",
           events != "caught_stealing_2b",
           events != "caught_stealing_3b",
           if_fielding_alignment == "Standard") %>% 
    mutate(hit = case_when(events == "single" | events == "double" | events == "triple" | events == "home_run" ~ "Y",
                           TRUE ~ "N"))
  
  ab_wos = (nrow(temp2)-sum(temp2$events=="hit_by_pitch")-sum(temp2$events == "sac_fly")-sum(temp2$events == "walk"))
  ba_wos = round(sum(temp2$hit == "Y")/ab_wos, 3)
  obp_wos = round((sum(temp2$hit == "Y")+sum(temp2$events == "walk")+sum(temp2$events == "hit_by_pitch")) /nrow(temp2), 3)
  slg_wos = round((sum(temp2$events == "single")+2*sum(temp2$events == "double")+3*sum(temp2$events == "triple")+4*sum(temp2$events == "home_run"))/ab_wos, 3)
  ops_wos = round(obp_wos+slg_wos, 3)
  
  ret = data.frame(ab_ws, ba_ws, obp_ws, slg_ws, ops_ws, ab_wos, ba_wos, obp_wos, slg_wos, ops_wos)
  return(ret)
}


graph_shift_stats = function(table){
  temp <- data.frame(type=c("AVG", "AVG", "OBP", "OBP", "SLG", "SLG", "OPS", "OPS"),
                     col =c("Shift", "No Shift", "Shift", "No Shift", "Shift", "No Shift", "Shift", "No Shift"),
                     data = c(table$ba_ws, table$ba_wos, table$obp_ws, table$obp_wos, table$slg_ws, table$slg_wos, table$ops_ws, table$ops_wos))
  
  ggplot(temp, aes(x=factor(type, level=c("AVG", "OBP", "SLG", "OPS")), y=data, fill=col))+
    geom_col(position = position_dodge())+
    scale_fill_manual(values= c("#3db5ff", "#0099f9"), name ="")+
    geom_text(aes(label=data), position = position_dodge(0.9), vjust=-.5, size = 4)+
    labs(x="", y="", title = "Slash Line With and Without Infield Shifts")
}
    
get_splits = function(sav_table){
  lefty <- sav_table %>% 
    filter(p_throws == "L",
           events != "",
           events != "caught_stealing_2b",
           events != "caught_stealing_3b")
  
temp = data.frame(Name = "Vs. Lefties", Age = "-", Team = "-", G = "-", PA = nrow(lefty), AB = nrow(lefty)-sum(lefty$events=="hit_by_pitch")-sum(lefty$events == "sac_fly")-sum(lefty$events == "walk"), R= "-", H = sum(lefty$events == "single")+sum(lefty$events == "double")+sum(lefty$events == "triple")+sum(lefty$events == "home_run"), Singles = sum(lefty$events == "single"), Doubles = sum(lefty$events == "double"), Triples = sum(lefty$events == "triple"), HR = sum(lefty$events == "home_run"), RBI = "-", BB = sum(lefty$events == "walk"), SO = sum(lefty$events == "strikeout"), HBP = sum(lefty$events == "hit_by_pitch"), SB = "-")
                  
BA = round(temp$H/temp$AB, 3)
OBP = round((temp$H+temp$BB+temp$HBP)/temp$PA, 3)
SLG = round((temp$Singles+2*temp$Doubles+3*temp$Triples+4*temp$HR)/temp$AB, 3)
OPS = OBP+SLG

temp = data.frame(temp, BA, OBP, SLG, OPS)

righty <- sav_table %>% 
  filter(p_throws == "R",
          events != "",
          events != "caught_stealing_2b",
          events != "caught_stealing_3b")
  
temp2 = data.frame(Name = "Vs. Righties", Age = "-", Team = "-", G = "-", PA = nrow(righty), AB = nrow(righty)-sum(righty$events=="hit_by_pitch")-sum(righty$events == "sac_fly")-sum(righty$events == "walk"), R= "-", H = sum(righty$events == "single")+sum(righty$events == "double")+sum(righty$events == "triple")+sum(righty$events == "home_run"), Singles = sum(righty$events == "single"), Doubles = sum(righty$events == "double"), Triples = sum(righty$events == "triple"), HR = sum(righty$events == "home_run"), RBI = "-", BB = sum(righty$events == "walk"), SO = sum(righty$events == "strikeout"), HBP = sum(righty$events == "hit_by_pitch"), SB = "-")
                  
BA = round(temp2$H/temp2$AB, 3)
OBP = round((temp2$H+temp2$BB+temp2$HBP)/temp2$PA, 3)
SLG = round((temp2$Singles+2*temp2$Doubles+3*temp2$Triples+4*temp2$HR)/temp2$AB, 3)
OPS = OBP+SLG

temp2 = data.frame(temp2, BA, OBP, SLG, OPS)

ret <- rbind(temp, temp2)
  
return(ret)
}   

graph_splits = function(pt){
    nt <- data.frame(type=c("AVG", "AVG", "OBP", "OBP", "SLG", "SLG", "OPS", "OPS"),
                   temp =c("Vs. Lefties", "Vs. Righties", "Vs. Lefties", "Vs. Righties", "Vs. Lefties", "Vs. Righties", "Vs. Lefties", "Vs. Righties"),
                   data = c(pt$BA[2], pt$BA[3], pt$OBP[2], pt$OBP[3], pt$SLG[2], pt$SLG[3], pt$OPS[2], pt$OPS[3]))
  ggplot(nt, aes(x=factor(type, level=c("AVG", "OBP", "SLG", "OPS")), y=data, fill=temp))+
    geom_col(position = position_dodge())+
    scale_fill_manual(values= c("#3db5ff", "#0099f9"), name ="")+
    geom_text(aes(label=data), position = position_dodge(0.9), vjust=-.5, size = 4)+
    labs(x="", y="", title = paste0("Lefty-Righty Slash Line of ", pt$Name))
}

```

```{r Shiny}
current = Sys.Date()

run_shiny = function() {
  shinyApp(
    ui = fluidPage(
      titlePanel("MLB Player Database"),
      mainPanel(tabsetPanel(
        tabPanel(
          "Stat page",
          sidebarPanel(
            textInput("player1", "Choose a Player:"),
            actionButton("run1", "Generate")
          ),
          uiOutput("text1"),
          tags$head(tags$style("#text1{font-size: 15px; text-align: center;}")),
          tableOutput("main_stats"),
          fluidRow(splitLayout(
            plotOutput("slash", width = 500, height = 500),
            plotOutput("split_slash", width = 500, height = 500)
          ))
        ),
        tabPanel(
          "Hit distrubion",
          sidebarPanel(
            textInput("player2", "Choose a Player:"),
            actionButton("run2", "Generate")),
          uiOutput("text2"),
          tags$head(tags$style("#text2{font-size: 20px; text-align: center;}")),
          fluidRow(splitLayout(
            plotOutput("spray", width = 500, height = 500),
            plotOutput("shift_bar", width = 500, height = 500)
          ))
          
        )
      )
      )
    ),
    server = function(input, output, session) {
      
      #stats panel
      observeEvent(input$run1, {
        if(input$player1 %in% br_data$Name){
          
          #get tables
          first_last <- as.data.frame(str_split(input$player1, ' '))
          player_id_table <- playerid_lookup(first_last[2, 1], first_last[1, 1])
          player_savant_table <- scrape_statcast_savant_batter(start, current, player_id_table$mlbam_id)
          curr_player_br_table <- br_data %>% 
            filter(Name == input$player1) %>% 
            rename("Singles"=X1B,
                   "Doubles"=X2B,
                   "Triples"=X3B) %>%
            mutate(Age = as.integer(Age), G = as.integer(G), PA = as.integer(PA), AB=as.integer(AB),R=as.integer(R),
                   H=as.integer(H), Singles=as.integer(Singles), Doubles=as.integer(Doubles), Triples = as.integer(Triples),
                   HR=as.integer(HR), RBI = as.integer(RBI), BB=as.integer(BB), SO=as.integer(SO), HBP=as.integer(HBP),
                   SB=as.integer(SB), BA = round(BA, 3), OBP = round(OBP, 3), SLG=round(SLG, 3), OPS=round(OPS,3)) %>% 
            select(Name, Age, Team, G, PA, AB, R, H, Singles, Doubles, Triples, HR, RBI, BB, SO, HBP, SB, BA, OBP, SLG, OPS)
          
          #
          if(input$player1 %in% qualifiers$Name){
            output$text1 <- renderText(
              paste0("<b>", input$player1, " ranks:", "</b>", "<br>",
                     "No. ", calc_rank(curr_player_br_table, "R"), " in runs,", "<br>",
                     "No. ", calc_rank(curr_player_br_table, "H"), " in hits,", "<br>", 
                     "No. ", calc_rank(curr_player_br_table, "RBI"), " in RBIs,", "<br>", 
                     "No. ", calc_rank(curr_player_br_table, "BA")[[1]][1], " in batting average (top ", calc_rank(curr_player_br_table, "BA")[[2]][1], "%),", "<br>", 
                     "No. ", calc_rank(curr_player_br_table, "OBP")[[1]][1], " in on-base percentage (top ", calc_rank(curr_player_br_table, "OBP")[[2]][1], "%),", "<br>", 
                     "No. ", calc_rank(curr_player_br_table, "SLG")[[1]][1], " in slugging percentage (top ", calc_rank(curr_player_br_table, "SLG")[[2]][1], "%),", "<br>", 
                     " No. ", calc_rank(curr_player_br_table, "OPS")[[1]][1], " in on-base + slugging (top ", calc_rank(curr_player_br_table, "OPS")[[2]][1], "%).", "<br>", 
                    "<br>", " "))
          }
          else{
            output$text1 <- renderText(paste0("<b>", input$player1, " ranks No.", "</b>", calc_rank(curr_player_br_table, "R")[1], " in runs, No.", calc_rank(curr_player_br_table, "H")[1], " in hits, No.", calc_rank(curr_player_br_table, "RBI")[1], " in RBIs.", "<br>", " "))
          }
          
          splits <- rbind(curr_player_br_table, get_splits(player_savant_table))
          output$main_stats <- renderTable(splits)
          output$slash <- renderPlot(graph_slashline2(curr_player_br_table))
          output$split_slash <- renderPlot(graph_splits(splits))
        }
        else output$text1 <- renderText("Please enter a valid player name.")
      })
      
      #spray chart panel
      observeEvent(input$run2, {
        if(input$player2 %in% br_data$Name){
          first_last <- as.data.frame(str_split(input$player2, ' '))
          player_id_table <- playerid_lookup(first_last[2, 1], first_last[1, 1]) 
          player_savant_table <- scrape_statcast_savant_batter(start, current, player_id_table$mlbam_id) %>% 
            mutate(result = case_when(grepl("out", des) | grepl("error", des) | grepl("fielder's choice", des) ~ "Out",
                                      grepl("single", des) ~"Single",
                                      grepl("double", des) ~"Double",
                                      grepl("triple", des) ~ "Triple",
                                      grepl("homer", des) | grepl("grand slam", des)~ "Homerun"))
          
          curr_player_br_table <- br_data %>% 
            filter(Name == input$player2) %>% 
            rename("Singles"=X1B,
                   "Doubles"=X2B,
                   "Triples"=X3B) %>%
            mutate(Age = as.integer(Age), G = as.integer(G), PA = as.integer(PA), AB=as.integer(AB),R=as.integer(R),
                   H=as.integer(H), Singles=as.integer(Singles), Doubles=as.integer(Doubles), Triples = as.integer(Triples),
                   HR=as.integer(HR), RBI = as.integer(RBI), BB=as.integer(BB), SO=as.integer(SO), HBP=as.integer(HBP),
                   SB=as.integer(SB), BA = round(BA, 3), OBP = round(OBP, 3), SLG=round(SLG, 3), OPS=round(OPS,3)) %>% 
            select(Name, Age, Team, G, PA, AB, R, H, Singles, Doubles, Triples, HR, RBI, BB, SO, HBP, SB, BA, OBP, SLG, OPS)
          
          player_shifts = shift_perc(player_savant_table, curr_player_br_table)
          shift_slash = get_shift_stats(player_savant_table)
          
          output$text2 <- renderText(paste0("<b>", input$player2, "</b>", " has been shifted on ", player_shifts$perc_bypa, "% of his at-bats (", player_shifts$pa_shift, " plate appearances). He has not been shifted against in ", (100-player_shifts$perc_bypa), "% of his plate appearances (", player_shifts$pa_no_shift, " plate appearances, ", player_shifts$perc_strategic_bypa, "% strategic \"shifts\").", "<br>", " "))
          output$spray <- renderPlot(spraychart(player_savant_table %>% filter(!is.na(hc_x))))
          output$shift_bar <- renderPlot(graph_shift_stats(shift_slash))
        }
        else output$text1 <- renderText("Please enter a valid player name.")
      })
      
    }
  )
}

run_shiny()
    
```

